# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0006_periodictask_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default=b'', max_length=4096, null=True)),
                ('author', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('text', models.TextField(null=True)),
                ('file_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default=b'', max_length=4096, null=True), null=True, size=None)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default=b'', max_length=4096, null=True), null=True, size=None)),
                ('youtube_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default=b'', max_length=4096, null=True), null=True, size=None)),
                ('soundcloud_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default=b'', max_length=4096, null=True), null=True, size=None)),
                ('size', models.IntegerField(default=0)),
                ('session_key', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default=b'', max_length=4096, null=True)),
                ('exception', models.CharField(max_length=1000, null=True)),
                ('traceback', models.TextField(null=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='static/export')),
                ('status', models.IntegerField(choices=[(1, '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (2, '\u0423\u0441\u043f\u0435\u0448\u043d\u043e'), (3, '\u041e\u0448\u0438\u0431\u043a\u0430')], default=1, null=True)),
                ('include_files', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, default=b'', max_length=4096, null=True)),
                ('path', models.CharField(max_length=200, null=True)),
                ('checksum', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('size', models.IntegerField(default=0)),
                ('session_key', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_every_amount', models.IntegerField(null=True)),
                ('start_every_type', models.CharField(choices=[('days', '\u041a\u0430\u0436\u0434\u044b\u0439 \u0434\u0435\u043d\u044c'), ('hours', '\u041a\u0430\u0436\u0434\u044b\u0439 \u0447\u0430\u0441'), ('minutes', '\u041a\u0430\u0436\u0434\u0443\u044e \u043c\u0438\u043d\u0443\u0442\u0443'), ('seconds', '\u041a\u0430\u0436\u0434\u0443\u044e \u0441\u0435\u043a\u0443\u043d\u0434\u0443')], max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(choices=[(1, '\u0417\u0430\u043f\u0443\u0449\u0435\u043d'), (2, '\u041e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d')], default=1, null=True)),
                ('last_run_at', models.DateTimeField(null=True)),
                ('last_session_key', models.CharField(max_length=50, null=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spider'),
        ),
        migrations.AddField(
            model_name='error',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spider'),
        ),
        migrations.AddField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files', to='core.File'),
        ),
        migrations.AddField(
            model_name='document',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spider'),
        ),
    ]
