# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='type',
            field=models.IntegerField(choices=[(1, '\u0410\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0439'), (2, '\u0420\u0443\u0447\u043d\u043e\u0439')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.IntegerField(choices=[(1, '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (2, '\u0423\u0441\u043f\u0435\u0448\u043d\u043e'), (3, '\u041e\u0448\u0438\u0431\u043a\u0430'), (4, '\u0421\u043a\u0430\u0447\u0430\u043d\u043e')], default=1, null=True),
        ),
    ]
