# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190603_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file',
            field=models.FileField(blank=True, upload_to='static/export/'),
        ),
    ]
