# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190605_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='additional_status',
            field=models.IntegerField(choices=[(1, '\u041e\u0441\u0442\u0430\u043d\u0430\u0432\u043b\u0438\u0432\u0430\u0435\u0442\u0441\u044f'), (2, '\u0412 \u043e\u0436\u0438\u0434\u0430\u043d\u0438\u0438'), (3, '\u0420\u0430\u0431\u043e\u0442\u0430\u0435\u0442'), (4, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d')], default=2, null=True),
        ),
    ]
