# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_exported_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='exported_archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Export'),
        ),
    ]
