# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190704_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='deleting',
            field=models.BooleanField(default=False),
        ),
    ]
