# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_export_deleting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_cols', models.IntegerField(default=0)),
                ('files_cols', models.IntegerField(default=0)),
                ('files_size', models.IntegerField(default=0)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spider')),
            ],
        ),
    ]
