# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_size_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_file', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('session_key', models.CharField(max_length=50, null=True)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spider')),
            ],
        ),
        migrations.RemoveField(
            model_name='size',
            name='spider',
        ),
        migrations.RemoveField(
            model_name='document',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='document',
            name='size',
        ),
        migrations.RemoveField(
            model_name='file',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='document',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AdditionalInformation'),
        ),
        migrations.AddField(
            model_name='file',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AdditionalInformation'),
        ),
    ]
